openapi: 3.0.0
info:
  title: BookSiginatureFinderService
  description: An API to generate all possible sets of signatures for the given range
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: localhost

paths:
  /list/{minPages}/{maxPages}:
    get:
      summary: Retrieve signature set for the target range
      description: For the given allowed values and range will produce all the available signature sets that produce a book with pages within that range
      parameters:
        - name: sizes
          in: query
          description: list of allowed signature sizes
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
            minItems: 1
        - name: min
          in: path
          description: minimum pages for book
          required: true
          schema:
            type: integer
            format: int64
            minimum: 4
        - name: max
          in: path
          description: maximum pages for book
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignatureList'
        '400':
          description: BAD REQUEST
  /{minPages}/{maxPages}:
    get:
      summary: Retrieve signature set for the target range
      description: For the given allowed values and range will produce all the available signature sets that produce a book with pages within that range
      parameters:
        - name: sizes
          in: query
          description: list of allowed signature sizes
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
            minItems: 1
        - name: min
          in: path
          description: minimum pages for book
          required: true
          schema:
            type: integer
            format: int64
            minimum: 4
        - name: max
          in: path
          description: maximum pages for book
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignatureString'
        '400':
          description: BAD REQUEST
components:
  schemas:
    SignatureListEntry:
      type: object
      properties:
        size:
          type: integer
        count:
          type: integer
    SignatureList:
      type: object
      required:
        - signatures
      properties:
        signatures:
          type: array
          items:
            $ref: '#/components/schemas/SignatureListEntry'
        pages:
          type: integer
    SignatureString:
      type: string

